<script setup>
import {reactive} from "vue";

const cols = reactive([
  {name: 'year', label: '年', width: '8', align: 'right'},
  {name: 'month', label: '月', width: '8', align: 'right'},
  {name: 'day', label: '日', width: '8', align: 'right'},
  {name: 'event', label: '事件', width: '56', align: 'left'},
  {name: 'step', label: 'step', width: '10', align: 'left'},
  {name: 'source', label: '出处', width: '10', align: 'left'},
])
const data = [
  {year: 'X-*年', month: '*月', day: '*日', event: '花名認識志溫，志溫為花名綁上心形髮型', source: '10卷彩頁'},
  {year: 'X-▲年', month: '*月', day: '*日', event: '志溫在櫻澤幼兒園看花名表演跳舞', step: 'step.69', source: '6卷70p'},
  {
    year: 'X-12年?',
    month: '*月',
    day: '*日',
    event: '志溫將借給○○社作為單身宿舍的公寓命名為租借住宅樓(音同剃光住宅樓)',
    step: 'step.7',
    source: '1卷65p'
  },
  {
    year: 'X-4年', month: '9~10月', day: 'a日', event: '榮依子在私立小學的見學週校內探險時遇到冠',
    step: 'step.54', source: '5卷46p'
  },
  {day: 'a+3日', event: '榮依子在第4天向冠打招呼', step: 'step.52', source: '5卷27p'},
  {day: 'a+4日', event: '見學週最後一天，榮依子初訪千石家', step: 'step.53', source: '5卷40p'},
  {day: 'a+5日', event: '冠找尋榮依子未果', step: 'step.54', source: '5卷44p'},
  {event: '千石家開始飼養和美与威美', source: '5卷45p'},
  {year: 'X-1年', month: '1~2月', day: '*日', event: '果實轉校至轉校至今泉中學', step: 'step.94', source: '8卷104p'},
  {day: '*日', event: '花名与丟失家裏鑰匙的果實相識', source: '8卷106p'},
  {month: '1~3月', day: '*日', event: '大會考試失利', step: 'step.13', source: '1卷115p'},
  {month: '2月', day: 'a日', event: '花名患上腮腺炎', step: 'step.2', source: '1卷17p'},
  {day: 'a+1日', event: '公立高中入學考試日', source: '1卷19p'},
  {month: '3月', day: '*日', event: '剛進入3月，果實搬家', step: 'step.94', source: '8卷111p'},
  {day: '*日', event: '大會高中畢業', step: 'step.11', source: '1卷99p'},
  {day: '*日', event: '志溫大學畢業，未能就職', step: 'step.2', source: '1卷24p'},
  {day: '*日', event: '大會開始在手鞠住宅樓生活'},
  {day: '*日', event: '志溫成為手鞠住宅樓管理者', step: 'step.2', source: '1卷24p'},
  {day: 'a日', event: '花名缺席初中畢業式', source: '1卷21p'},
  {day: 'b日', event: '所有高中均已過入學考試期', source: '1卷22p'},
  {event: '花名痊癒', source: '1卷22p'},
  {month: '*月', day: '*日', event: '綴向創談起髪型', step: 'step.81', source: '7卷86p'},
  {year: 'X-1年', month: '春', event: '花名開始在手鞠住宅樓生活', source: '21-10'},
  {month: '6~7月', day: '*日', event: '冠在街上看到光希', step: 'step.22', source: '2卷83p'},
  {month: '9月?', day: '*日', event: '玉手參加星尾女子高中見學', step: 'step.78', source: '7卷46p'},
  {year: 'X年', month: '1~2月', day: '*日', event: '星尾女子高中入學考試日', source: '7卷53p'},
  {event: '榮依子遇到榎並老師', source: '7卷53p'},
  {month: '3月', day: '*日', event: '玉手、榮依子初中畢業式', step: 'step.21', source: '2卷72p'},
  {event: '學生會長内海向榮依子告白', step: 'step.21', source: '2卷73p'},
  {year: 'X年', month: '4月', day: '*日', event: '十倉家開始飼養稀助', source: '2卷尾頁'},
  {day: '6日', event: '星尾女子高中入學式', step: 'step.1', source: '1卷9p'},
  {event: '花名17歲生日', source: '1卷12p'},
  {event: '冠煩惱身高未漲，將髮帶解開', source: '5卷彩頁'},
  {day: '7日', event: '花名猜測未被記住名字', source: '1卷16p'},
  {day: 'a日(土or日)', event: '花名與母親通電話', step: 'step.3', source: '1卷25p'},
  {day: 'b日(月)', event: '志溫：“過完週末”，榮依子：“相識第4天”', source: '1卷28p'},
  {day: 'c日', event: '聊妹汁', step: 'step.4', source: '1卷33p'},
  {day: 'd日', event: 'スポーツテスト', step: 'step.5', source: '1卷41p'},
  {event: '發現冰淇淋自動販賣機', step: 'step.6', source: '1卷53p'},
  {day: 'e日(日)', event: '花名和志溫慢跑時遇到帶稀助散步的榮依子', step: 'step.7', source: '1卷57p'},
  {day: 'e+1日(月)', event: '花名得知志溫就職失利', source: '1卷64p'},
  {day: 'f日', event: '聊黃金週計劃', step: 'step.8', source: '1卷67p'},
  {day: 'g日', event: '黃金週開始', step: 'step.9', source: '1卷75p'},
  {month: '4~5月', day: '*日', event: '花名父母來手鞠住宅樓探望', source: '1卷77p'},
  {day: '*日', event: '榎並在家喝酒頭髮和拼圖粘在一起', step: 'step.11', source: '1卷94p'},
  {month: '5月', day: 'a日', event: '志溫回老家', step: 'step.10', source: '1卷83p'},
  {day: 'a+1日', event: '黃金週最後一天在花名的房間開學習會', source: '1卷83p'},
  {day: 'a+2日', event: '發現榎並的頭髪剪短', step: 'step.11', source: '1卷93p'},
  {event: '花名初識大會', source: '1卷98p'},
  {day: 'b日', event: '聊玉手箱=玉+手箱', step: 'step.12', source: '1卷103p'},
  {day: 'c日(土or日)', event: '花名和大會講失學話題', step: 'step.13', source: '1卷111p'},
  {event: '玉手、榮依子、冠拜訪大會房間', step: 'step.14', source: '2卷12p'},
  {event: '大家一起去幫大會挑衣服', step: 'step.15', source: '2卷20p'},
  {day: '*日', event: '創建四天王群組，因花名是翻蓋手機擱置', step: 'step.76', source: '7卷33p'},
  {month: '6月', day: 'a日', event: '換夏季校服', step: 'step.16', source: '2卷25p'},
  {day: 'b日', event: '玉手進行壁櫥大掃除', step: 'step.17', source: '2卷34p'},
  {day: 'b+1日', event: '玉手在學校玩galgame', source: '2卷34p'},
  {day: 'c日', event: '大會煩惱衣服下襬如何處理', step: 'step.18', source: '2卷41p'},
  {event: '花名煩惱榮依子的生日禮物', source: '2卷45p'},
  {day: 'c+1日', event: '玉手猜中花名要送的禮物', source: '2卷48p'},
  {day: '20日', event: '榮依子16歲生日', step: 'step.19', source: '2卷51p'},
  {day: 'd日', event: '花名和高橋值日', step: 'step.20', source: '2卷61p'},
  {day: 'd+1日', event: '花名決心下次自己道早安', source: '2卷68p'},
  {month: '6~7月', day: 'a日', event: '確定學習會計劃', step: 'step.21', source: '2卷69p'},
  {day: 'b日', event: '花名、玉手在學校初識光希', step: 'step.22', source: '2卷80p'},
  {day: 'c日', event: '玉手戴上奶奶的戒指無法取下', step: 'step.23', source: '2卷89p'},
  {day: 'd日', event: '榮依子遇到醉酒的榎並', step: 'step.24', source: '2卷99p'},
  {event: '榮依子在榎並家中留宿', source: '2卷103p'},
  {day: 'd+1日', event: '留宿次日', source: '2卷97p'},
  {day: 'f日', event: '榮依子在椿森家遇襲', step: '話間/卷末', source: '2卷108p'},
  {day: 'g日', event: '花名收到母親給的零花錢', step: 'step.25', source: '2卷115p'},
  {day: 'h日', event: '花名收到母親寄的衣服', source: '2卷118p'},
  {day: 'i日', event: '牙科檢查', step: '話間/卷末', source: '3卷116p'},
  {month: '7月', day: 'a日', event: '在花名房間開學習會，留宿', step: 'step.26', source: '3卷9p'},
  {day: 'a+1日', event: '留宿次日', step: 'step.27', source: '3卷24p'},
  {day: 'b日', event: '大家一起去買泳衣', step: 'step.28', source: '3卷28p'},
  {day: 'c日', event: '風紀検査', step: 'step.29', source: '3卷33p'},
  {day: 'd日', event: '冠值日，得到榎並送的棒棒糖', step: 'step.30', source: '3卷43p'},
  {day: 'e日(土?)', event: '花名母親留宿手鞠住宅樓2晚', step: 'step.31', source: '3卷51p'},
  {day: 'e+1日(日?)', event: '花名母親遇到榎並', step: 'step.32', source: '3卷65p'},
  {day: 'e+2日(月?)', event: '花名、榮依子值日，榮依子講手工飾品的事', step: 'step.33', source: '3卷73p'},
  {day: 'f日', event: '榮依子送給花名手工別針飾品', source: '3卷78p'},
  {day: 'g日', event: '天氣很熱', step: 'step.34', source: '3卷79p'},
  {day: 'h日', event: '花名夢到向大家訴說失學', step: 'step.35', source: '3卷87p'},
  {event: '上學起晚，忘記摘耳塞', step: 'step.35', source: '3卷89p'},
  {event: '忘記拿便當', step: 'step.36', source: '3卷96p'},
  {day: 'i日', event: '聊社會實踐', step: 'step.37', source: '3卷107p'},
  {day: 'j日', event: '學期結業式', step: 'step.38', source: '4卷7p'},
  {day: 'j+1日', event: '暑假開始，冠去海外旅遊', step: 'step.39', source: '4卷16p'},
  {event: '學習強化合宿', source: '4卷17p'},
  {day: 'j+2日', event: '榮依子感冒早退', source: '4卷25p'},
  {day: 'k日', event: '在菜農處買番茄', step: 'step.40', source: '4卷27p'},
  {day: '*日', event: '大會輔導班暑期課開始', step: 'step.38', source: '4卷13p'},
  {day: 'l日', event: '去海邊前夜留宿花名家', step: 'step.41', source: '4卷36p'},
  {day: 'l+1日', event: '大雨無法去海邊，冠展示聽聲辯硬幣', source: '4卷37p'},
  {day: '*日', event: '一之瀨家開始飼養堅果', source: '6卷彩頁'},
  {event: '雨停，去戶外温水泳池', step: 'step.45', source: '4卷72p'},
  {month: '8月', day: 'a日', event: '花名：“高中過去4個月”', step: 'step.46', source: '4卷75p'},
  {day: 'a+1日', event: '花名晨間散步，遇到帶稀助散步的榮依子', source: '4卷77p'},
  {day: 'b日', event: '榮依子、光希試穿參加表姐愛里的結婚典禮用的禮服', step: 'step.47', source: '4卷83p'},
  {
    day: 'c日',
    event: '花名、在家庭旅遊地點(附近的山上)遇到同樣在家庭旅遊的冠，並向父母介紹冠',
    step: 'step.48',
    source: '4卷91p'
  },
  {event: '玉手和榮依子出門玩，在去相約地點前相遇，幫助老奶奶尋路，榮依子被搭訕', source: '4卷84p'},
  {day: 'd日', event: '花名在大會房間一起吃巧克力', step: 'step.49', source: '4卷105p'},
  {day: 'e日', event: '大家一起購物，添置烤薄餅靠墊', step: 'step.50', source: '5卷7p'},
  {day: 'f日', event: '榮依子收到千石父親贈禮冰淇淋，拜訪千石家', step: 'step.51', source: '5卷23p'},
  {day: 'g日', event: '花名重新開始慢跑', step: 'step.55', source: '5卷53p'},
  {event: '玉手品嚐家庭自製糖浆', step: 'step.55', source: '5卷56p'},
  {event: '榮依子在冠家聊水族館', step: 'step.55', source: '5卷57p'},
  {day: 'h日', event: '小堀美彌子出門約會', step: 'step.56', source: '5卷61p'},
  {event: '志溫與大會“約會”', step: 'step.56', source: '5卷64p'},
  {event: '四天王出門拍課題照片', source: '5卷65p'},
  {event: '大家齊聚在燒烤店', step: 'step.57', source: '5卷71p'},
  {day: 'i日', event: '暑假最後一天，冠和榎並逛甜點店中相遇，興趣相投', step: 'step.58', source: '5卷87p'},
  {day: 'i+1日', event: '第2學期開始', step: 'step.58', source: '5卷83p'},
  {event: '屬於暑假會提前結束的地區', source: '@1093yuiko2018.08.16'},
  {day: 'j日', event: '冠測量了身長，長高了2釐米', step: 'step.59', source: '5卷94p'},
  {day: 'j+1日', event: '第一次去學校食堂', source: '5卷93p'},
  {event: '玉手因發胖長襪總是掉', source: '5卷96p'},
  {day: 'k日', event: '大會害怕坐電車', step: 'step.60', source: '5卷101p'},
  {day: 'l日', event: '榮依子穿著3年級顏色的室內鞋', step: 'step.61', source: '5卷109p'},
  {event: '榮依子與山岸再會', step: 'step.61', source: '5卷111p'},
  {event: '與兆野綴相識', step: 'step.61', source: '5卷116p'},
  {day: 'l+1日', event: '綴在課間來花名班上', step: 'step.63', source: '6卷17p'},
  {day: 'm日', event: '玉手聊自己做的夢', step: 'step.62', source: '6卷10p'},
  {day: 'm+1日', event: '榮依子、榎並，夢到對方', source: '6卷15p'},
  {day: 'n日', event: '排球課後，花名將榮依子叫錯為媽媽', step: 'step.64', source: '6卷29p'},
  {event: '新刊發售日', step: 'step.64', source: '6卷32p'},
  {event: '榮依子、冠，感情難於傳達，難以得知。', step: 'step.64', source: '6卷33p'},
  {day: 'o日', event: '不二軟餅特別發售日，花名、大會與冠、榎並相遇，返程與綴相遇', step: 'step.65', source: '6卷35p'},
  {event: '冠、榎並與榮依子匯合', step: 'step.65', source: '6卷41p'},
  {day: 'p日', event: '玉手在花名家開學習會', step: 'step.66', source: '6卷43p'},
  {event: '榮依子在千石家開大吃會', source: '6卷44p'},
  {event: '大會在輔導班與溝端創相遇', source: '6卷45p'},
  {day: 'q日', event: '玉手夢到榮依子和榎並', step: 'step.68', source: '6卷66p'},
  {month: '9月', day: 'a日', event: '本週體育課教跳舞', step: 'step.69', source: '6卷70p'},
  {event: '在9月初旬', source: '@1093yuiko2018.08.16'},
  {day: 'b日', event: '商討文化祭', step: 'step.70', source: '6卷77p'},
  {event: '把你做成骷髏頭開始流行一段時間', source: '6卷84p'},
  {day: 'c日', event: '花名閑來無事，在家學習', step: 'step.71', source: '6卷85p'},
  {day: 'd日', event: '聊社團話題', source: '6卷86p'},
  {day: 'e日', event: '文化祭準備期間', step: 'step.72', source: '6卷93p'},
  {event: '榮依子、冠幫助綴與社團交涉，冠收穫零食', step: 'step.72', source: '6卷98p'},
  {event: '四天王在學生會幫忙', step: 'step.72', source: '6卷101p'},
  {event: '學生會決定製作T恤', step: 'step.72', source: '6卷104p'},
  {event: '學生會T恤圖案商討', step: 'step.73', source: '6卷105p'},
  {day: 'f日', event: '學生會T恤製作完成', source: '6卷112p'},
  {day: 'g日', event: '準備文化祭', step: 'step.74', source: '7卷9p'},
  {event: '聊各社團T恤圖案', step: 'step.74', source: '7卷10p'},
  {day: 'h日', event: '百地家冰箱壞了', step: 'step.75', source: '7卷17p'},
  {event: '在百地家開大吃會', source: '7卷21p'},
  {day: 'h+1日', event: '玉手撐掉校服裙子的釦子', source: '7卷26p'},
  {day: '*日', event: '玉手父母週末回國1週', source: '7卷18p'},
  {day: 'i日', event: '花名丟失一個交通安全的繪馬', step: 'step.76', source: '7卷27p'},
  {event: '花名的翻蓋手機故障，買了新的智能手機', source: '7卷31p'},
  {day: 'j日', event: '四天王線上群組啟用，第一枚紀念照片是豬肉蓋飯', source: '7卷34p'},
  {day: '*日', event: '加入1年2班群組、學生會群組、一之瀨家庭群組', source: '7卷34p'},
  {day: 'k日', event: '學校組織參加垃圾清理志願活動，榮依子被搭訕', step: 'step.77', source: '7卷36p'},
  {event: '花名撿到大會錢包，並於站前派出所歸還', step: 'step.77', source: '7卷39p'},
  {day: 'l日', event: '光希來星尾女子高中見學，換上榮依子校服', step: 'step.78', source: '7卷45p'},
  {event: '榮依子偷偷穿上光希校服，下樓逗貓時遇到榎並', step: 'step.78', source: '7卷49p'},
  {day: 'm日', event: '志溫房間的鎖故障', step: 'step.80', source: '7卷73p'},
  {day: 'm+1日', event: '從志溫房間發現警用叉', source: '7卷78p'},
  {day: 'n日', event: '四天王在花名房間玩警用叉', source: '7卷80p'},
  {day: 'o日', event: '玉手，睡過頭', step: 'step.81', source: '7卷81p'},
  {day: 'p日', event: '換髪型', source: '7卷87p'},
  {day: 'q日', event: '花名和玉手看電影，榮依子在店中添置新作手工飾品', step: 'step.82', source: '7卷89p'},
  {event: '冠和榎並一起去雑貨店將榮依子的新作飾品買走', step: 'step.83', source: '7卷101p'},
  {event: '冠和榎並逛甜點店，和榮依子匯合，榎並離開', step: 'step.82', source: '7卷92p'},
  {event: '冠和榮依子、花名和玉手在蕎麥麵店相遇', source: '7卷98p'},
  {day: 'r日', event: '榮依子在冠家看相冊，講手工飾品的事', step: 'step.83', source: '7卷102p'},
  {day: 's日', event: '榮依子和玉手講手工飾品的事', source: '7卷104p'},
  {month: '10月', day: 'a日', event: '換冬季校服', step: 'step.84', source: '7卷107p'},
  {event: '聊女教師話題', source: '7卷109p'},
  {day: 'b日', event: '和美威美，長胖了', step: 'step.85', source: '8卷7p'},
  {day: 'c日', event: '冠、榎並逛甜點店，商談如何給和美威美減肥', source: '8卷8p'},
  {day: '*日', event: '冠、和榮依子商談如何給和美威美減肥', source: '8卷8p'},
  {day: 'd日', event: '冠和玉手商談如何給和美威美減肥', source: '8卷14p'},
  {day: '*日', event: '冠編製出減肥奏法', source: '8卷15p'},
  {day: 'e日', event: '文化祭準備', step: 'step.86', source: '8卷17p'},
  {day: 'f日', event: '舞蹈練習', step: 'step.88', source: '8卷33p'},
  {day: '*日', event: '果實轉校至星尾女子高中'},
  {day: 'g日', event: '花名母親，偷偷到手鞠住宅樓探望', step: 'step.90', source: '8卷65p'},
  {day: 'h日', event: '花名夢到向大家訴說失學', step: 'step.91', source: '8卷75p'},
  {event: '花名與億果實再會', step: 'step.92', source: '8卷86p'},
  {event: '花名向大家訴說失學，果實回憶與花名的對話', step: 'step.93', source: '8卷96p'},
  {event: '花名早退，受涼發燒睡一整天', step: 'step.96', source: '9卷10p'},
  {day: 'h+1日', event: '花名、展示隨身梗後冷場', source: '9卷16p'},
  {event: '花名和母親通電話', source: '9卷18p'},
  {day: 'i日', event: '花名和大會跑步中遇到十倉姉妹和稀助', step: 'step.97', source: '9卷21p'},
  {day: 'j日', event: '文化祭準備，榮依子後宮事件→玉手後宮事件', step: 'step.98', source: '9卷31p'},
  {event: '綴將果實帶到學生會室', step: 'step.98', source: '9卷31p'},
  {day: 'k日', event: '還有大概10天文化祭，學生開始使用虛擬對話軟件並建立群組', step: 'step.100', source: '9卷49p'},
  {day: 'k+1日', source: '9卷56p'},
  {day: 'l日', event: '模擬店鋪海報開始展示，美術部完成星尾祭展示牌', step: 'step.101', source: '9卷59p'},
  {event: '女僕裝展示', step: 'step.101', source: '9卷64p'},
  {day: 'm日', event: '消失的糖果與被盯上的學生會事件，怪盜髮卡流行一段時間', step: 'step.102', source: '9卷67p'},
  {day: 'n日', event: '文化祭分發小冊子完成，玉手注意到果實的宅屬性', step: 'step.103', source: '9卷77p'},
  {day: 'n+1日', event: '分發小冊子與家人入場券', source: '9卷78p'},
  {event: '大會請榮依子當天幫忙打扮', source: '9卷81p'},
  {day: 'o日(土)', event: '星尾祭第1天', step: 'step.104', source: '9卷85p'},
  {event: '四天王父母集結，榮依子父親與玉手父親判明工作關係', step: 'step.106', source: '9卷108p'},
  {event: '四天王光顧2年1班女僕咖啡店', step: 'step.107', source: '9卷109p'},
  {event: '果實與花名約定出門玩，與綴約定第二天一起逛文化祭', source: '9卷114p'},
  {day: 'o+1日(日)', event: '星尾祭第2天', step: 'step.108', source: '10卷9p'},
  {event: '光希與朋友光顧星尾祭', source: '10卷9p'},
  {event: '四天王光顧園藝部', source: '10卷11p'},
  {event: '幸對榮依子下藥', source: '10卷15p'},
  {event: '榮依子初中朋友光臨星尾祭', step: 'step.109', source: '10卷20p'},
  {event: '玉手朋友光臨星尾祭', source: '10卷21p'},
  {event: '冠的小初朋友代表光臨星尾祭，交換聯繫方式', source: '10卷23p'},
  {event: '觀看戲劇部公演', step: 'step.110', source: '10卷29p'},
  {day: 'o+2日(月)', event: '調休日，花名和果實出門玩', step: 'step.111', source: '10卷15p'},
  {event: '玉手榮依子通電話，玉手去東京購物下館子', step: 'step.112', source: '10卷45p'},
  {event: '冠被貓淘氣捆綁，向榮依子通電話，榮依子急忙趕去', step: 'step.112', source: '10卷47p'},
  {day: 'o+3日(火)', event: '果實與大家稱呼變更', step: 'step.113', source: '10卷54p'},
  {event: '學生會早會，成為學生會成員', source: '10卷57p'},
  {day: '*日', event: '隔壁男子學校文化祭', step: 'step.108', source: '10卷17p'},
  {day: 'p日', event: '移動教室1日目', step: 'step.114', source: '10卷61p'},
  {event: '玉手向花名訴說嫉妒心', source: '10卷64p'},
  {day: 'p+1日', event: '移動教室2日目', step: 'step.115', source: '10卷70p'},
  {day: 'p+2日', event: '移動教室3日目'},
  {day: 'p+3日', event: '期中考試', step: 'step.114', source: '10卷62p'},
  {day: 'q日', event: '正式決定學生會職位', step: 'step.115', source: '10卷73p'},
  {day: 'q+1日', event: '花名睡回籠覺差點遲到/入學已半年', step: 'step.116', source: '10卷82p'},
  {event: '冠就任學生會長', step: 'step.117', source: '10卷91p'},
  {day: 'r日', event: '花名和創聊身體同樣虛弱', step: 'step.117', source: '10卷88p'},
  {day: 's日', event: '體育祭', step: 'step.118', source: '10卷99p'},
  {day: 's+1日', event: '調休日', step: 'step.121',source: '11卷26p'},
  {day: 't日', event: '果實發覺自己的gal宅屬性',step: 'step.122', source: '11卷30p'},
  {day: 'u日', event: '玉手觀看過去的動画',step: 'step.123', source: '11卷39p'},
  {day: '30日', event: '冠16歲生日',step: 'step.124', source: '11卷45p'}
]
</script>

<template>
  <el-table height="80vh" :data="data">
    <el-table-column v-for="col in cols" :header-align="col.align" :align="col.align" :prop=col.name :label=col.label
                     :min-width="col.width">
    </el-table-column>
  </el-table>

</template>

<style scoped>

</style>